# Generated by Django 3.0.9 on 2020-09-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0004_auto_20200907_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'paid')], default=0),
        ),
    ]
