# Generated by Django 3.0.9 on 2020-09-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0005_auto_20200908_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
