# Generated by Django 3.0.9 on 2020-10-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_created_at'),
        ('payments', '0008_videolectureorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_for',
        ),
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
    ]
