# Generated by Django 3.0.9 on 2020-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_membership_subscription_usermembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='external_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
