# Generated by Django 3.0.9 on 2020-10-15 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0014_auto_20201014_1810'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermembership',
            unique_together={('user', 'membership')},
        ),
    ]
