# Generated by Django 3.0.9 on 2020-10-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_subscription_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
