# Generated by Django 3.0.9 on 2020-11-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocoursepackage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='videocoursepackage',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='videolecturepackage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='videolecturepackage',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
