# Generated by Django 3.0.9 on 2020-11-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20201117_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocoursepackage',
            name='image',
            field=models.ImageField(null=True, upload_to='coursepackage_pictures/'),
        ),
        migrations.AddField(
            model_name='videolecturepackage',
            name='image',
            field=models.ImageField(null=True, upload_to='videolecture_package_pictures/'),
        ),
    ]
