stages:
  - lint
  - test
  - deploy

variables:
  POSTGRES_USER: 'afi_backend'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_afi_backend'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

flake8:
  stage: lint
  image: python:3.7-alpine
  before_script:
    - pip install -q flake8
  script:
    - flake8

pytest:
  stage: test
  image: python:3.7
  image: docker/compose:latest
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker-compose -f local.yml build
    # Ensure celerybeat does not crash due to non-existent tables
    - docker-compose -f local.yml run --rm django python manage.py migrate
    - docker-compose -f local.yml up -d
  script:
    - docker-compose -f local.yml run django pytest

development:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=fierce-dawn-98824 --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master
