# Generated by Django 3.0.9 on 2020-09-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineLecture',
            fields=[
                ('lecturebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.LectureBase')),
                ('address', models.TextField()),
            ],
            bases=('events.lecturebase',),
        ),
    ]
