# Generated by Django 3.0.9 on 2020-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_offlinelecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='event_type',
        ),
        migrations.AlterField(
            model_name='lecturebase',
            name='lecture_summary_file',
            field=models.FileField(blank=True, null=True, upload_to='lecture_summaries/'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='lecturer_userpics/'),
        ),
    ]
