# Generated by Django 3.0.9 on 2020-09-11 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200909_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinelecture',
            name='lecture_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
