# Generated by Django 3.0.9 on 2020-09-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200914_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureRatingAdmin',
            fields=[
                ('lecturerating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.LectureRating')),
            ],
            bases=('events.lecturerating',),
        ),
        migrations.AlterModelOptions(
            name='lecturecategory',
            options={'verbose_name_plural': 'Lecture categories'},
        ),
    ]
