# Generated by Django 3.0.9 on 2020-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_lecturecategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinelecture',
            name='capacity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
