# Generated by Django 3.0.9 on 2020-09-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_offlinelecture_capacity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectureCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
