# Generated by Django 3.0.9 on 2020-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200918_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturebase',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lecturebase',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lecturebase',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lecturebase',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
