# Generated by Django 3.0.9 on 2020-09-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200921_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinelecture',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offlinelecture',
            name='address_ru',
            field=models.TextField(null=True),
        ),
    ]
