# Generated by Django 3.0.9 on 2020-09-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_auto_20200921_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLectureCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='video_lecture_certificates/')),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('lecturebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.LectureBase')),
                ('link', models.URLField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.VideoLectureCertificate')),
            ],
            bases=('events.lecturebase',),
        ),
        migrations.CreateModel(
            name='OnlineLectureBulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('video_lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='events.VideoLecture')),
            ],
        ),
    ]
