# Generated by Django 3.0.9 on 2020-09-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_videolecture_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolecture',
            name='customer',
        ),
    ]
