# Generated by Django 3.0.9 on 2020-10-07 06:44

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_videolecture_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturebase',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1'), default_currency='RUB', max_digits=10, null=True),
        ),
    ]
