# Generated by Django 3.0.9 on 2020-10-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201007_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturebase',
            options={'ordering': ['id']},
        ),
    ]
