# Generated by Django 3.0.9 on 2020-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20201019_1328'),
        ('events', '0019_auto_20201012_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolecture',
            name='allowed_memberships',
            field=models.ManyToManyField(to='payments.Membership'),
        ),
    ]
