# Generated by Django 3.0.9 on 2020-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_videolecture_allowed_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolecture',
            name='link',
        ),
        migrations.AddField(
            model_name='videolecture',
            name='vimeo_video_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
