# Generated by Django 3.0.9 on 2020-09-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200921_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='user_userpics/', verbose_name='userpic'),
        ),
    ]
