# Generated by Django 3.0.9 on 2020-10-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0002_auto_20201012_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocourse',
            options={'ordering': ['id']},
        ),
    ]
