# Generated by Django 3.0.9 on 2020-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_subscription_due'),
        ('videocourses', '0003_auto_20201014_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='allowed_memberships',
            field=models.ManyToManyField(to='payments.Membership'),
        ),
    ]
