# Generated by Django 3.0.9 on 2020-10-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0005_auto_20201016_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselecture',
            name='lecture_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videocourses.LectureTest'),
        ),
        migrations.AlterField(
            model_name='courselecture',
            name='video_link',
            field=models.FileField(upload_to='videcourses/{self.course.name}/'),
        ),
    ]
