# Generated by Django 3.0.9 on 2020-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0006_auto_20201016_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselecture',
            name='video_link',
            field=models.FileField(upload_to='videcourses_lectures/'),
        ),
    ]
