# Generated by Django 3.0.9 on 2020-11-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0009_remove_courselecture_lecture_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='LectureTest',
        ),
        migrations.AddField(
            model_name='videocourse',
            name='course_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videocourses.VideoCourseType'),
        ),
    ]
