# Generated by Django 3.0.9 on 2020-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0010_auto_20201112_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselecture',
            name='video_link',
        ),
        migrations.AddField(
            model_name='courselecture',
            name='vimeo_video_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
