# Generated by Django 3.0.9 on 2020-11-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0011_auto_20201113_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocoursepart',
            name='picture',
            field=models.ImageField(null=True, upload_to='videocourse_part_pictures/'),
        ),
    ]
