# Generated by Django 3.0.9 on 2020-10-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
