# Generated by Django 3.0.9 on 2020-09-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200914_1425'),
        ('payments', '0006_payablemixin'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='object_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='offline_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.OfflineLecture'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payablemixin_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.PayableMixin'),
            preserve_default=False,
        ),
    ]
