# Generated by Django 3.0.9 on 2020-09-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='event_type',
            new_name='content_type',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
