# Generated by Django 3.0.9 on 2020-09-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200907_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='ticket',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tickets.Ticket'),
        ),
    ]
