# Generated by Django 3.0.9 on 2020-10-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
