# Generated by Django 3.0.9 on 2020-11-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Progress'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='result',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
