# Generated by Django 3.0.9 on 2020-11-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20201106_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='answered',
        ),
        migrations.AddField(
            model_name='progress',
            name='chosen_answers',
            field=models.ManyToManyField(to='exams.Answer'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Progress'),
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
