# Generated by Django 3.0.9 on 2020-11-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20201107_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='exams.Progress'),
        ),
    ]
