# Generated by Django 3.0.9 on 2020-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20201113_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_picture',
            field=models.ImageField(blank=True, null=True, upload_to='test_pictures/'),
        ),
    ]
