log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "developer@artforintrovert.ru"
      storage: /etc/traefik/acme/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-router:
      rule: "Host(`dev.artforintrovert.ru`)"

      entryPoints:
        - web
      middlewares:
        - redirect
      service: frontend

    web-secure-router:
      rule: "Host(`dev.artforintrovert.ru`)"

      entryPoints:
        - web-secure
      service: frontend
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`dev.artforintrovert.ru`)"
      entryPoints:
        - flower
      service: flower
      # tls:
      #   # https://docs.traefik.io/master/routing/routers/#certresolver
      #   certResolver: letsencrypt

  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: http
        permanent: true

  services:
    frontend:
      loadBalancer:
        servers:
          - url: http://frontend:4000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
