log:
  level: "DEBUG"

api:
  dashboard: true

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "developer@artforintrovert.ru"
      storage: /etc/traefik/acme/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    robots:
      rule: "Host(`dev.artforintrovert.ru`) && Path(`/robots.txt`)"
      service: django
      entryPoints:
        - web
      middlewares:
        - redirect

    robots-secure:
      rule: "Host(`dev.artforintrovert.ru`) && Path(`/robots.txt`)"
      service: django
      entryPoints:
        - web-secure
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    drf-api:
      rule: "Host(`dev.artforintrovert.ru`) && PathPrefix(`/api`)"
      service: django
      entryPoints:
        - web
      middlewares:
        - redirect

    drf-secure-api:
      rule: "Host(`dev.artforintrovert.ru`) && PathPrefix(`/api`)"
      service: django
      entryPoints:
        - web-secure
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    dashboard:
      rule: "(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      service: api@internal
      middlewares:
        - auth
        - redirect

    web-router:
      rule: "Host(`dev.artforintrovert.ru`)"
      entryPoints:
        - web
      middlewares:
        - redirect
      service: frontend

    web-secure-router:
      rule: "Host(`dev.artforintrovert.ru`)"

      entryPoints:
        - web-secure
      service: frontend
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`dev.artforintrovert.ru`)"
      entryPoints:
        - flower
      service: flower
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt


  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: http
        permanent: true
    auth:
      basicAuth:
        users:
          - "test:$apr1$pwy2cslb$2pXFRaZtsXW/CKgBzqq9L1"

  services:
    frontend:
      loadBalancer:
        servers:
          - url: http://frontend:4000

    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
